# Generated by Django 4.2.20 on 2025-05-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gitn', models.CharField(max_length=14)),
                ('location', models.CharField(max_length=200)),
                ('buy_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
