# Generated by Django 4.2.20 on 2025-06-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gitn', models.CharField(max_length=14)),
                ('location', models.CharField(max_length=200)),
                ('buy_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='expiry_date',
            new_name='expiry_date_min',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='buy_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='location',
        ),
        migrations.AddField(
            model_name='inventory',
            name='counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
