# Generated by Django 4.2.20 on 2025-06-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_rename_gitn_inventory_gtin_rename_gitn_item_gtin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='order',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='item',
            name='imageurl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
