# Generated by Django 4.2.20 on 2025-06-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_remove_item_order_item_image_item_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='imageurl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
