# Generated by Django 4.2.20 on 2025-06-06 21:12

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_alter_item_image_alter_item_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='expiry_date_min',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='buy_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.AddField(
            model_name='inventory',
            name='buy_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='inventory',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='gtin',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
