# Generated by Django 4.2.20 on 2025-06-07 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_remove_inventory_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
