# Generated by Django 4.2.20 on 2025-06-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0009_item_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
