# Generated by Django 4.2.20 on 2025-06-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0010_item_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
