# Generated by Django 4.2.20 on 2025-06-07 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0011_alter_item_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='expiry_date',
            field=models.DateField(default=datetime.date(9999, 12, 31)),
        ),
    ]
