# Generated by Django 4.2.20 on 2025-06-07 17:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_inventory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='imageurl',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
