# Generated by Django 4.2.20 on 2025-06-07 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0014_remove_inventory_id_alter_inventory_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='gtin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='hello.item'),
        ),
    ]
